spring:
  application:
    name: fileshare
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:nextudb
    username: sa
    password:
server:
  port: 8081
  servlet:
    context-path: /api